<?php
/** @var $block \Sergei\News\Block\PostView */
/** @var $post \Sergei\News\Model\Post */
$post = $block->getPost();
?>
<h1 class="blog-post-item-title"><?php echo $post->getTitle() ?></h1>

<div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
        <div class="blog-post-item-content">
            <?php echo $post->getContent(); ?>
        </div>

        <div class="blog-post-item-meta">
            <strong><?php echo __('Created at:') ?></strong> <?php echo $post->getCreationTime() ?>
        </div>
    </div>
</div>